name: CI
on: [push]
env:
  GO111MODULE: on

jobs:
  build:
    name: Build, Test & Analyse with ${{ matrix.go }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.11, 1.12, 1.13]

    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Format using gofmt
        run: go fmt ./...

      - name: Run static analysis using vet
        run: go vet ./...

      - name: Compile code
        run: go build ./...

      - name: Run all tests with coverage
        run: go test -v -coverprofile=coverage.out ./...

      - name: Coveralls service
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ./coverage.out
          github-token: ${{ secrets.GITHUB_TOKEN }}
